# Generated by Django 5.2.10 on 2026-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=5)),
                ('kind', models.CharField(choices=[('dep', 'Departure'), ('arr', 'Arrival')], max_length=3)),
                ('flight_date', models.CharField(max_length=8)),
                ('std', models.CharField(max_length=4)),
                ('airline', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('flight_no', models.CharField(max_length=10)),
                ('status', models.CharField(default='정상', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['airport_code', 'kind', 'flight_date', 'std'], name='dashboard_f_airport_97795e_idx')],
                'unique_together': {('airport_code', 'kind', 'flight_date', 'std', 'flight_no', 'origin', 'destination')},
            },
        ),
    ]
