-- [V] Sequence : 순차번호 생성기, 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ
    START WITH 101  -- 101 부터 생성(기본값:1)
    INCREMENT BY 10 -- 증감치(기본값:1), 현재는 10씩 증가
    MAXVALUE 9999   -- 최댓값(감소를 사용하면 MINVALUE)
    NOCYCLE         -- 최댓값을 넘어도 사이클이 돌지 않음(최댓값을 넘어서면 에러)
    NOCACHE;        -- 캐시메모리 사용 안함
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; -- NEXTVAL(순차번호 생성), DUAL:오라클 제공 테이블
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL(현재까지 진핸된 순차번호)

-- EX. 시퀀스를 이용한 FRIEND 테이블
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20),
    ADDRESS VARCHAR2(300),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 99999 NOCACHE NOCYCLE;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번 실행 가능
SELECT * FROM FRIEND;
SELECT NO,NAME,TEL,ADDRESS,
    TO_CHAR(LAST_MODIFY,'RR/MM/DD AM HH:MI:SS') LAST_MODIFY
    FROM FRIEND;
INSERT INTO FRIEND
    VALUES (FRIEND_SQ.NEXTVAL, '김길동', '010-9988-9999', '봉천', SYSDATE); -- 만약 TEL에 UNIQUE를 썼다면 여러번 실행 시 오류
    
-- 연습문제

-- 테이블, 시퀸스 삭제
    DROP TABLE MEMBER;
    DROP TABLE MEMBER_LEVEL;
    DROP SEQUENCE MEMBER_MNO_SQ;
-- 테이블, 시퀸스 생성
    CREATE TABLE MEMBER_LEVEL(
        LEVELNO NUMBER(1) PRIMARY KEY,
        LEVELNAME VARCHAR2(6)
    );
    CREATE TABLE MEMBER(
        mNO NUMBER(4) PRIMARY KEY,
        mNAME VARCHAR2(20) NOT NULL,
        mPW VARCHAR2(8) NOT NULL,
        mEMAIL VARCHAR2(30) UNIQUE,
        mPOINT NUMBER(9) CHECK(mPOINT>=0),
        mRDATE DATE DEFAULT SYSDATE,
        LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
    );
    CREATE SEQUENCE MEMBER_MNO_SQ NOCACHE;
-- MEMBER_LEVEL 내용 삽입
    INSERT INTO MEMBER_LEVEL VALUES(-1,'black');
    INSERT INTO MEMBER_LEVEL VALUES(0,'일반');
    INSERT INTO MEMBER_LEVEL VALUES(1,'실버');
    INSERT INTO MEMBER_LEVEL VALUES(2,'골드');
    SELECT * FROM MEMBER_LEVEL;
    COMMIT;
-- MEMBER 내용 삽입
    INSERT INTO MEMBER VALUES(MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('24/09/26','RR/MM/DD'), 0);
    INSERT INTO MEMBER VALUES(MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('22/04/01','RR/MM/DD'), 1);
    SELECT * FROM MEMBER;
    COMMIT;
-- 내용 출력
    SELECT mNO "mNO", mNAME "mNAME", mRDATE "mRDATE", mEMAIL "mMAIL", mPOINT "point", LEVELNAME || '고객' "levelname"
        FROM MEMBER MB, MEMBER_LEVEL MBL
        WHERE MB.LEVELNO = MBL.LEVELNO;
    
    
    
    
    
    
    
    
    
    