# Generated by Django 5.2.10 on 2026-01-28 02:09

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sales',
            field=models.IntegerField(default=1000, validators=[book.models.salesCheek], verbose_name='판매가'),
        ),
    ]
